on: 
    push:
         branches: [  ]
name: react-storybook
jobs:
    build:
      name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      defaults:
        run:
          working-directory: packages/react
      strategy:
        matrix:
          node: ['10.x', '12.x', '14.x']
          os: [ubuntu-latest, windows-latest, macOS-latest]

      steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Use Node ${{ matrix.node }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node }}

        - name: Install deps and build (with cache)
          run: npm install --force

        - name: Build
          run: npm run build
